version: "3.8"

volumes:
  pgdata:

networks:
  restaurant_net:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: restaurante
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin2525
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - restaurant_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - restaurant_net

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin2525
      - DB_DATABASE=restaurante
      - DB_PORT=5432
      - PORT=3000
    networks:
      - restaurant_net

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3002:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin2525
      - DB_DATABASE=restaurante
      - DB_PORT=5432
      - PORT=3000
    networks:
      - restaurant_net

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - restaurant_net
